#set heading(numbering: none, outlined: true)
#set cite(style: "apa")

= Guidelines for the Use of AI-Assisted Tools in Theses

== General Guidelines: Transparency and Responsibility

The use of AI-based tools (e.g., ChatGPT, DeepL Write, GitHub Copilot) in academic work can be helpful but requires responsible handling. Two fundamental principles apply:

- *Transparency:* The use of AI tools must be disclosed. It must be made clear which tools were used, exactly what they were used for, and which passages are affected @limburg2022.
- *Responsibility:* Full responsibility for the content of the work remains with the author. Even when using AI-generated suggestions, verification and, if necessary, revision are mandatory.

These principles align with the European Commission's recommendations for the responsible use of generative AI in research @eu2025generativeAI, which identify *accountability*, *transparency*, and the *integrity of the research process* as central criteria.

Before using AI tools, *consultation with the supervisor* is necessary, particularly to clarify which forms of usage are acceptable in the given context @eth_bib @tum_bib.

== Disclosure in the Declaration of Authorship

The disclosure of AI usage is provided via a tabular overview at the end of the thesis (see section _Overview of Auxiliary Materials Used_) as a declaration regarding the use of AI tools @jaschke2023. The Declaration of Authorship refers to this table. This is based on expanded wording following the recommendations of institutions such as TU Darmstadt @tudarmstadt_bib or LMU Munich @lmu_bib.

== Examples of Entries in the List of Auxiliary Materials

- *ChatGPT (OpenAI, GPT-4, May 2025):* Structural assistance for Chapter 1, rephrasing in Section 2.3. Prompt examples documented in the appendix.
- *DeepL Write:* Linguistic smoothing of the entire body text. Style check performed before submission.
- *GitHub Copilot:* Completion of individual code segments (e.g., Listing 3). Manual revision and testing performed.
- *Claude 3 (Anthropic):* Support with text compression and section titles in Chapter 4.
- For translation purposes.
- For literature research.
- For finalizing the work—in the sense of proofreading (linguistic and stylistic adjustments), optimization (e.g., using AI-generated feedback; for revisions see @frankfurt2023).
- For the development/optimization/finalization of software source code.
- During the creation of individual chapters, sub-chapters, or specific passages, which are marked accordingly.
- Creation of visualizations and diagrams.

Current templates and recommendations can be found at ETH Zurich @eth_bib, TUM @tum_bib, or LMU Munich @lmu_bib.

== Use of LLMs as Programming Tools
Tools such as GitHub Copilot, Claude Code, Amazon CodeWhisperer, or ChatGPT are increasingly used as assistance systems in programming. They can assist, for example, in writing functions, organizing projects, finding syntax errors, or understanding external code. It is important to note that in these areas, generated suggestions must always be critically examined—for instance, through testing—and an understanding of the generated functionality must be established. It is often necessary to adapt generated code components and integrate them meaningfully into one's own context. A good introduction to the reflective use of such tools can be found in the blog post by Simon Willison @willison2025.

== Note on Citing AI-Generated Responses
If generative AI systems are used—in agreement with the supervisor—it must be clearly recognizable to readers "which parts of the text were generated by an AI and to what extent" (@salden2023didaktische, page 29). For verbatim adoptions, it is recommended to treat these like a quotation @salden2023didaktische.

If specific formulations or statements are taken from an AI tool (e.g., an analysis, a definition, or a quote), this passage must be marked as a *citation* @ucl2023. Note that many tools do not represent a stable source. Recommended practice:

- Cite as: _"Response from ChatGPT, OpenAI, Version GPT-4, accessed May 20, 2025"_.
- Alternatively: Reference the stored prompt and response in the appendix.

ETH Zurich recommends documenting the complete prompt-response combination @eth_bib. Further information can also be found at LMU Munich @lmu_bib.

#v(1em)
*Further Reading:*
- Detailed general recommendations on dealing with generative AI in studies and teaching from Goethe University Frankfurt @frankfurt2023
- @schmid_bib – Overview of copyright issues when using generative AI
- @eth_bib – Official ETH Zurich page on AI and plagiarism
- @tum_bib – TUM formal requirements with AI notice
- @willison2025 – Notes on the use of LLMs in programming
